
// Array holding the possible button colors in the Simon game
var buttonColors = ["red", "blue", "green", "yellow"];

// Stores the sequence generated by the game
var gamePattern = [];

// Stores the sequence of colors clicked by the user
var userClickedPattern = [];

// Tracks the current level of the game
var currentLevel = 0; 

// Boolean to check if the game has started
var started = false; 


// Start the game on any keypress if not already started
$(document).keypress( function () {
    if(!started){
        nextSequence(); 
        started = true; 
    }
});


// Handle user button clicks
$('.btn').click( function(){
    var userChosenColor = $(this).attr("id"); // Get the id (color) of the clicked button
    userClickedPattern.push(userChosenColor); // Add user's choice to their pattern
    flashButton(userChosenColor); // Animate the button press and play sound
    checkAnswer(userClickedPattern.length - 1); // Check the user's answer
})


// Go to next level, add a random color, reset user pattern
function nextSequence() {
    console.log("Start of nextSequence")
    userClickedPattern = [];
    currentLevel++; 
    $("h1").text("Level " + currentLevel); 

    // Randomly select a color and add to the game pattern
    var randomNumber = Math.floor(Math.random() * 4);
    var randomChosenColor = buttonColors[randomNumber];

    gamePattern.push(randomChosenColor);

    flashButton(randomChosenColor);
}


// Flash the button and play its sound
function flashButton(color) {
    $("#" + color).fadeIn(100).fadeOut(100).fadeIn(100);
    playSound(color);
}


// Play sound for a color
function playSound(color){
    var sound = new Audio('sounds/' + color + '.mp3');
    sound.play().catch( e => console.log("Audio play failed: ", e));
}

// Check user's answer, go to next level or end game
function checkAnswer(index){
    if(gamePattern[index] === userClickedPattern[index]){
        // If user has finished the sequence correctly, go to next level
        if(gamePattern.length === userClickedPattern.length){
            setTimeout( function(){
                nextSequence();  
            }, 1500);
        }
    } else{
        // If user made a mistake, end the game and show feedback
        startOver();    
        $("body").addClass("game-over"); 
        setTimeout( function(){
                $("body").removeClass("game-over");
        }, 200);
        playSound("wrong")
    }
}

// Reset game state after wrong answer
function startOver() {
    currentLevel = 0;
    gamePattern = [];
    started = false;
    $("h1").text("Game Over, Press Any Key to Restart");
}